### ISSUE TITLE
Idea - take advantage of existing OpenAPIParser

### ISSUE THREAD

**Issue by Dzoukr** [Zaid-Ajaj/Hawaii#1]
Hello friend, I am looking forward to what your next awesome thing will be. When I saw you're working with OpenAPI, I was thinking: maybe take a look at the existing F# parser lib I did some time ago: https://github.com/Dzoukr/OpenAPIParser

It has some limits but it can easily parse yaml (or json) into definition https://github.com/Dzoukr/OpenAPIParser/blob/master/src/OpenAPIParser/Version3/Specification.fs and that could be a good starting point for the generator you are writing.

Just an idea. Discard this message when read. 😄 All the best with the new Zaid's awesomeness! 💪

**Comment by Zaid-Ajaj** [comment]
Hi Roman, I actually checked out your parser a while ago and I really like the [SchemaDefinition](https://github.com/Dzoukr/OpenAPIParser/blob/master/src/OpenAPIParser/Version3/Specification.fs#L46-L62) but [OpenAPIParser#2](https://github.com/Dzoukr/OpenAPIParser/issues/2) is a real blocker for me because of the missing `anyOf`, `oneOf` definitions 😢 

For now I am going with [Microsoft.OpenApi.Readers](https://github.com/microsoft/OpenAPI.NET) and planning on building functional constructs on top of it. That is unless it turns that it doesn't resolve the external references like your parser does 😉

**Comment by Dzoukr** [comment]
Damn... I should finish the `anyOf` and `oneOf` then 😄

**Comment by Zaid-Ajaj** [comment]
That would be awesome 😍

**Comment by Zaid-Ajaj** [comment]
Sorry Roman, the project got pretty tied to the OpenAPI reader API (since I really needed their customized [external resource loader](https://github.com/Zaid-Ajaj/Hawaii/blob/master/src/Program.fs#L1800-L1820) functionality) thanks again for the suggestion.

If you happen to have an OpenAPI service to test hawaii against, would be happy to hear how it turns out 😉

**Comment by Dzoukr** [comment]
No problem at all, my friend! I admire your ability to turn a proof-of-concept into production stuff so quickly! 💪🎉
