### ISSUE TITLE
Throws StackOverflowException

### ISSUE THREAD

**Issue by petrkoutnycz** [Zaid-Ajaj/Hawaii#42]
Hi, I was trying to generate a client for Mews API and it fails when generating properties.

Swagger: https://api.mews.com/Swagger/connector/swagger.yaml

**Comment by Zaid-Ajaj** [comment]
Hi there @petrkoutnycz, I will have a look! It could be due to recursive definitions in the schema. Will let you know how it goes

**Comment by petrkoutnycz** [comment]
@Zaid-Ajaj thank you!

**Comment by Zaid-Ajaj** [comment]
Hi @petrkoutnycz I was able to debug and fix the issue  that gets you the stack overflow error as of Hawaii v0.61 :rocket:

The problem was in the definition of `CoproductParameters` where it uses a reference to `JToken`. Here is a subset of the schema you provided that reproduces the issue:
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "ConnectorApi",
    "version": "v1"
  },
  "components": {
    "schemas": {
      "CoproductParameters": {
        "type": "object",
        "properties": {
          "Discriminator": {
            "type": "string",
            "nullable": true
          },
          "Value": {
            "$ref": "#/components/schemas/JToken"
          }
        },
        "additionalProperties": false
      },
      "JToken": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/JToken"
        }
      }
    }
  }
}
```

As you can see, the definition of `JToken` is just `list<JToken>` which is an invalid type definition. To workaround this issue if you have access to the schema, you can change it so that `JToken` is an empty type definition `{ }`. You can use the [Overriding schema feature](https://github.com/Zaid-Ajaj/Hawaii#advanced---overriding-the-schema) of Hawaii to achieve this.

**Comment by petrkoutnycz** [comment]
@Zaid-Ajaj thanks for your response!
